# Generated by Django 4.1.3 on 2022-11-22 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='todo',
            name='start_date',
            field=models.DateField(),
        ),
    ]
