# Generated by Django 4.1.3 on 2022-11-23 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_todo_is_deleted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='end_date',
            new_name='end_at',
        ),
        migrations.RenameField(
            model_name='todo',
            old_name='start_date',
            new_name='start_at',
        ),
    ]
