# Generated by Django 4.1.3 on 2022-11-25 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_rename_end_date_todo_end_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='user',
            new_name='author',
        ),
    ]
